main: com.ustmc.core.main
name: TigerMC
version: 1.22
author: Justin Ruaya
depend: [WorldGuard, Vault, LuckPerms]
softdepend: [SkinsRestorer]
description: Utilities plugin used in the UST Minecraft server.

commands:
  tigermc:
    description: Displays plugin version or reload.
    usage: /tigermc (reload) 
    permission: tigermc.main.reload
  hug:
    description: Sends a wireless virtual hug to someone! Be sure you're still 5 blocks near, though.
    usage: /hug <player>
  poke:
    description: Pokes a person! Nudge them when they're not paying attention!
    usage: /poke <player>
  fuck:
    description: C'mon... seriously?
    usage: /fuck
  trackplayer:
    description: Locates a person by updating the compass.
    usage: /trackplayer <player>
  createshop:
    description: TO BE DELETED; automates shops for university tower 
    usage: /createshop <roomnumber>
  crush:
    description: Admires a person. He/she won't know until you like each other.
    usage: /crush <online player>
  uncrush:
    description: Deletes a person from your crush list. Make sure the player hasn't change name since you /crush him/her.
    usage: /uncrush <player>
  test:
    description: Tests a command
    usage: /test <player>
  sanaol:
    description: Para sa mga mag-jowang makulit.
    usage: /sanaol <player1> <player2>
  tigerplayer:
    description: Edits, reads and writes attributes to a person.
    usage: /tigerplayer <attributes> <player|me> <set|remove|read> <index> <value>
  tigerwhitelist:
    description: Whitelist commands.
    usage: /tigerwhitelist <manualadd|manualremove|blacklist|list|update> (PLayer Name | Colleges) (College)
  uniform:
    description: Wear uniforms. During events, you can't do this.
    usage: /uniform <wear|remove|list>
  bell:
    description: Rings the bell.
    usage: /bell 
permissions:
  tigermc.core.reload:
   description: Allows people to reload the plugin.
   default: op
  tigermc.*:
    description: Allows all permission-bound commands to be executed.
    default: op
    children:
      tigermc.core.reload: true
      tigermc.social.sanaol: true
      tigermc.player.tigerplayer: true
  tigermc.social.sanaol:
    description: Throws people.
    default: op
  tigermc.player.tigerplayer:
    description: Modifies player attributes.
    default: op
  tigermc.player.tigerwhitelist:
    description: Whitelist manager
    default: op
  tigermc.admin.uniform:
    description: Admin override of uniforms.
    default: op
  tigermc.admin.bell:
    description: Rings the bell for the entire campus.
    default: op